title: Homelab
theme: dark
color: slate
headerStyle: clean
layout:
  Infrastructure:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 2
  Media:
    style: row
    columns: 4
  Cloud:
    style: row
    columns: 3
  AI:
    style: row
    columns: 2
