services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - DOMAIN=https://vaultwarden.local.wilfredtuscano.com
      - SIGNUPS_ALLOWED=false
    ports:
      - "8082:80"
    volumes:
      - ./data:/data
    restart: unless-stopped
