services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
      - VERSION=docker
    volumes:
      - ./config:/config
      - /mnt/nfs/media/Movies:/movies
      - /mnt/nfs/media/Series:/series
      - /mnt/nfs/media/Music:/music
    restart: unless-stopped
    network_mode: host
