services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    ports:
      # Firefox HTTP
      - 3000:3000
      # Firefox HTTPS
      - 3001:3001
      # QBT UI Port
      - 8090:8090
      # Bittorrent port
      - 56881:56881
      - 56881:56881/udp

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
      - WEBUI_PORT=8090
      - TORRENTING_PORT=56881
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/nfs/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ./firefox/config:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
