services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - TZ=US/Pacific
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ./prowlarr/config:/config
    ports:
      # Prowlarr port
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ./radarr/config:/config
      - /mnt/nfs/media/Movies:/movies
      - /mnt/nfs/downloads:/downloads
      - /mnt/nfs/recycle-bin/Movies:/recycle-bin
    ports:
      # Radarr port
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ./sonarr/config:/config
      - /mnt/nfs/media/Series:/series
      - /mnt/nfs/downloads:/downloads
      - /mnt/nfs/recycle-bin/Series:/recycle-bin
    ports:
      # Sonarr port
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ./lidarr/config:/config
      - /mnt/nfs/media/Music:/music
      - /mnt/nfs/downloads:/downloads
      - /mnt/nfs/recycle-bin/Music:/recycle-bin
    ports:
      # Lidarr port
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ./readarr/config:/config
      - /mnt/nfs/media/Books:/books
      - /mnt/nfs/downloads:/downloads
      - /mnt/nfs/recycle-bin/Books:/recycle-bin
    ports:
      # Readarr port
      - 8787:8787
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    restart: unless-stopped
    volumes:
      - /mnt/nfs/downloads/metube:/downloads
    ports:
      - 8081:8081
